### ISSUE TITLE
Replace use of appraisal gem with a standard travis-ci build matrix

### ISSUE THREAD

**Issue by rmm5t** [thoughtbot/shoulda-context#41]
See #40. We still want to support ruby 1.8 syntax, but we need a more robust build matrix to only test Ruby 1.8.7 against dependency version that also still support ruby 1.8.
- [ ] Remove appraisal gem and config
- [ ] Design a travis-ci build matrix that covers all of our current scenarios without failing on incompatible dependency combinations.

I'll start on this as soon as I can.

**Comment by mcmire** [comment]
Closing this issue as it's really old, and we seem to have been using Travis's build matrix to run tests across multiple Rubies already (and, with updates I just made, Minitest and Test::Unit as well).
