### ISSUE TITLE
Setup and teardown hooks leak across contexts

### ISSUE THREAD

**Issue by cluesque** [thoughtbot/shoulda-context#44]
I sometimes use a macro to install setup and teardown hooks.  And expect those hooks not to be run in contexts outside the ones I install them in.

It seems (sometimes?) those setup macros get run inappropriately.

Consider:

```
  def self.setup_setup_helper
    setup { @wrapped = true }
    teardown{ @wrapped = false }
  end
  context "outer nesting" do
    context 'irrelevant' do
      setup_setup_helper
      should 'not matter' do
        assert @wrapped
      end
    end
    context "without setup" do
      setup do
        puts "inner explicit setup"
      end
      should 'not have run the other setup' do
        assert !@wrapped
      end
    end
  end
```

In the `irrelevant` block I expect (and assert) that the setup is not run.  But it is.

Note that the `inner explicit setup` setup block is not executed in the `irrelevant` context.

This is demonstrated in a rails project with just `shoulda` and `shoulda-context` at [shoulda_context_demo](https://github.com/cluesque/shoulda_context_demo)

**Comment by mcmire** [comment]
Closing as this is an old issue, and this doesn't seem like a bug. The problem with your example was that `setup` and `teardown` were getting defined immediately, outside of your "outer nesting" context. In case anyone else runs across this, you should be able to do this by wrapping both the `setup` and `teardown` in a proc and then `instance_eval`ing that proc within the context(s) you want:

``` ruby
setup_setup_helper = proc do
  setup { @wrapped = true }
  teardown { @wrapped = false }
end

context "outer nesting" do
  context 'irrelevant' do
    instance_eval(&setup_setup_helper)
    should 'not matter' do
      assert @wrapped
    end
  end
  context "without setup" do
    setup do
      puts "inner explicit setup"
    end
    should 'not have run the other setup' do
      assert !@wrapped
    end
  end
end
```
