### ISSUE TITLE
Need help for setting up shoulda-context framework

### ISSUE THREAD

**Issue by talktokets** [thoughtbot/shoulda-context#47]
I am a Software Test Engineer and want to automate my web app using shoulda framework. I have referred multiple sources but unable to know how it is to be done. 

I am automating using Selenium+ruby. For implementing shoulda-context framework what are the basic mandatory requirement like gems etc?

Also this kind of statement when I tried in my code, 

`class CalculatorTest < Test::Unit::TestCase
`

​it results in error.

​Also using this part ​`< Test::Unit::TestCase`​ is necessary?

**Comment by croaky** [comment]
@talktokets Can you try adding `require "test/unit"` to the top of your file? `Test::Unit::TestCase` is a class in Ruby's standard library http://ruby-doc.org/stdlib-1.8.7/libdoc/test/unit/rdoc/Test/Unit.html but may need to be required before it can be used.

**Comment by talktokets** [comment]
Thanks for helping me out. I will try adding it.

**Comment by talktokets** [comment]
I have added the above said line of code.
Now my code is:
```

class P_testing < Test::Unit::TestCase  
  context "Checking website : " do
  setup do
    open_website
  end
end
```

Now here it shows me the error as: `undefined method `context' for P_testing:Class (NoMethodError)`

Not sure what went wrong. I have setup everything correctly. Do I need to require any specific gems? I have already required "test/unit"

Please help.

**Comment by mjankowski** [comment]
Can you paste the full test file, and also your Gemfile?

**Comment by talktokets** [comment]
Hi,

I am pasting the content of my test file here. Also I have not created Gemfile as of now but I am pasting the gem list:

**gem list**
bigdecimal (1.2.0)
CFPropertyList (2.2.8)
childprocess (0.5.9)
ffi (1.9.10)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (4.3.2)
multi_json (1.11.2)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rdoc (4.0.0)
rubyzip (1.1.7)
scope (0.2.3)
selenium-webdriver (2.48.1)
shoulda-context (1.2.1)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
websocket (1.2.2)
```

require 'selenium-webdriver'
require "test/unit"

WAIT= Selenium::WebDriver::Wait.new(:timeout=>60)

def implicit_wait sleeptime
  $driver.manage.timeouts.implicit_wait = sleeptime
end

#Opening website
def open_website
  begin
    unless $driver.find_element(:xpath, "html/body/div[1]/div[1]/div/div[1]").displayed?
      raise "Failed to load website completely"
    end
    $driver.manage.timeouts.implicit_wait = 8
  rescue Exception => e
    STDERR.puts e.message
    raise e.message
  end
end


class P_testing < Test::Unit::TestCase  
  context "Checking website : " do
  setup do
    open_website
  end
end
end

```

Please check and let me know what exactly I am missing here.

**Comment by mjankowski** [comment]
can you elaborate more on:

> Also I have not created Gemfile as of now but I am pasting the gem list

Is this just a list of gems you have installed on your system?

If you're not using bundler or some other way to require the gems, you need to add something like

> require "shoulda/context"

to the top of that file.

**Comment by talktokets** [comment]
Yes. This is the only list of gems I have on my system.

Currently I am not using bundler, if needed I can use it. So for now require "shoulda/context" will be sufficient?

**Comment by mjankowski** [comment]
It should stop that error you were seeing about "context" being an unknown method, at least.

Beyond that, I'm not sure what you're doing here.
