### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by TastyPi** [thoughtbot/shoulda-context#72]
There hasn't been any commits since 2020 despite there being a few pull requests that seem like good changes. Also it looks @mcmire was the sole committer, but looking at their profile they've left thoughtbot so presumably they no longer have access to maintain this project?

@mcmire do you know if there is a good person to contact at thoughtbot to figure out who should be responsible for maintaining this gem going forwards?

I'd really like to get https://github.com/thoughtbot/shoulda-context/pull/71 merged, but it's not clear that will ever happen unless I cause a stink :slightly_smiling_face:.

**Comment by mcmire** [comment]
Hi @TastyPi,

Thanks for highlighting your PR. The shoulda gems are technically still owned by thoughtbot, so they always have access to these repos, but in practice all of the shoulda gems are currently maintained by @VSSPedro and myself. I will admit, however, that `shoulda-matchers` gets more love than this repo, and I haven't been involved much in the past couple of years. That said I just merged in some of the lingering PRs in this repo. I also responded to your PR. I'll try to keep an eye on it the next few days.
