### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by shayani** [thoughtbot/shoulda-context#90]
I'm a little afraid to continue using this gem since the last update was on Sep 21.

Is it still maintained? Are there alternatives to organize Rails MiniTest specs?

Thanks!

**Comment by bbenno** [comment]
Last commit is from September 21, 2023 (1 month ago)
Not sure whether GitHub's label "Sept 21" may be somewhat misleading at first glance.

**Comment by shayani** [comment]
> Last commit is from September 21, 2023 (1 month ago) Not sure whether GitHub's label "Sept 21" may be somewhat misleading at first glance.

Oh! Really sorry about that. It was a misreading on my part.

I now feel more comfortable to continue using it :) 
Thanks for the nice gem!
