### ISSUE TITLE
Push new release

### ISSUE THREAD

**Issue by segiddins** [thoughtbot/shoulda-context#96]
Hi there!

It seems like there are a number of improvements since v2.0.0 (https://github.com/thoughtbot/shoulda-context/compare/v2.0.0...main) and it would be awesome to have them in a release.

Thanks!

**Comment by vsppedro** [comment]
Thank you for opening this issue! I think we can close this: https://github.com/thoughtbot/shoulda-context/releases/tag/v3.0.0.rc1
